version: "3.7"

services:
  frontend:
    build: Streamlit_Frontend
    ports:
      - 8501:8501

  backend:
    build: FastAPI_Backend
    ports:
      - 8000:8000
    container_name: fastapi # and within frontend app  prediction_url should be "http://fastapi:8000/prediction"