version: "3.7"

services:
  frontend:
    build: Streamlit_Frontend
    ports:
      - 8501:8501
    # networks:
    #   AIservice:
    #     aliases:
    #       - frontend.docker
    # depends_on:
    #   - backend
    volumes:
      - ./Streamlit_Frontend:/app
      - ./storage:/storage
  backend:
    build: FastAPI_Backend
    ports:
      - 8000:8000
    #   networks:
    #     AIservice:
    #       aliases:
    #         - backend.docker
    volumes:
      - ./FastAPI_Backend:/app
      - ./storage:/storage
networks:
  internal-network:
    internal: true
  external-network: null

